language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

cache:
  directories:
    - $HOME/.m2/repository

script:
  - mvn clean package

after_success:
  - bash <(curl -s https://codecov.io/bash)